# 開発環境用
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-todo-app
    ports:
      - '13306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'todo_app'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: 'Asia/Tokyo'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
  app:
    image: todo_app:latest
    container_name: springboot-todo-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - gradle-cache:/home/gradle/.gradle
    working_dir: /app
    command: ["sh", "-c", "./gradlew bootRun"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todo_app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql-data:
  gradle-cache:
