# 開発環境用
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-todo-app
    ports:
      - '13306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'todo_app'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

volumes:
  mysql-data:
