spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/todo_app
    username: root
    password: root
  sql:
    init:
      mode: always
      schema-locations: classpath:database/schema.sql
      data-locations: classpath:database/data.sql
  thymeleaf:
    cache: false

mybatis:
  config-location: classpath:mybatis-config.xml
